---
title: "MB5 Fribble Survey"
author: "Jessica E. Kosie"
date: "2024-04-18"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(here)

```
# Read in and clean data
```{r read in data, echo = FALSE}
survey_data_raw <- read_csv(here("data", "fribble_survey_data_4.19.24.csv"))

#separate out base ratings and format long data file
base_data <- survey_data_raw %>% 
  select(RecipientFirstName, RecipientLastName, contains("base")) %>% 
  filter(!row_number() %in% 1:3) %>%  #get rid of excess rows
  mutate(response_number = 1:9) %>% #add a response number
  select(response_number, everything()) %>%  #sort to put response number first
  select(-RecipientFirstName, -RecipientLastName, -choose_12_bases) %>% 
  pivot_longer(2:ncol(.), names_to = "item", values_to = "rating") %>% 
  mutate(rating = parse_number(rating),
         item = str_remove(item, "_base"))

#separate out appendage ratings and format long data file
appendage_data <- survey_data_raw %>% 
  select(RecipientFirstName, RecipientLastName, contains("appendage")) %>% 
  filter(!row_number() %in% 1:3) %>%  #get rid of excess rows
  mutate(response_number = 1:9) %>% #add a response number
  select(response_number, everything()) %>%  #sort to put response number first
  select(-RecipientFirstName, -RecipientLastName) %>% 
  pivot_longer(2:ncol(.), names_to = "item", values_to = "rating") %>% 
  mutate(rating = parse_number(rating)) %>% 
  separate(item, into = c("item", "remove", "appendage_number")) %>% 
  select(-remove)

#get appendage and base data
appendage_and_bases <- base_data %>% 
  mutate(appendage_number = "base") %>% 
  bind_rows(appendage_data)

#separate out 12 chosen bases and format long data file
choice_data <- survey_data_raw %>% 
  select(RecipientFirstName, RecipientLastName, contains("choose")) %>% 
  filter(!row_number() %in% 1:3) %>%  #get rid of excess rows
  mutate(response_number = 1:9) %>% #add a response number
  select(response_number, everything()) %>%  #sort to put response number first
  select(-RecipientFirstName, -RecipientLastName) %>% 
  separate(choose_12_bases, c("choice_1", "choice_2", "choice_3", "choice_4", "choice_5", "choice_6", "choice_7", "choice_8", "choice_9", "choice_10", "choice_11", "choice_12")) %>% 
  pivot_longer(2:ncol(.), names_to = "choice_number", values_to = "item") %>% 
  na.omit()

#separate out entire item ratings and format long data file
by_item_data <- survey_data_raw %>% 
  select(RecipientFirstName, RecipientLastName, contains("entire")) %>% 
  filter(!row_number() %in% 1:3) %>%  #get rid of excess rows
  mutate(response_number = 1:9) %>% #add a response number
  select(response_number, everything()) %>%  #sort to put response number first
  select(-RecipientFirstName, -RecipientLastName) %>% 
  pivot_longer(2:ncol(.), names_to = "item", values_to = "rating") %>% 
  mutate(rating = parse_number(rating)) %>% 
  mutate(item = str_remove(item, "_entire"))

```
# Get average ratings for each base shape and plot.
```{r bases, echo = FALSE}

base_data %>% 
  group_by(item) %>% 
  summarise(avg_rating = mean(rating, na.rm = TRUE)) %>% 
  ggplot(aes(x = reorder(item, -avg_rating), y = avg_rating, fill = item)) +
  geom_bar(stat = "identity") +
  theme(legend.position = "none", axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  labs(x = "Base Shape", y = "Rating")

base_data %>% 
  ggplot(aes(x = item, y = rating, fill = item)) +
  geom_boxplot() +
  geom_point(aes(x = item, y = rating), position=position_jitter(width =.15), size = 2, shape = 1) +
  theme(legend.position = "none", axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  labs(x = "Base Shape", y = "Rating")

```
# Get average ratings for each appendage and plot.
```{r appendages, echo = FALSE}

appendage_data %>% 
  group_by(item, appendage_number) %>% 
  summarise(avg_rating = mean(rating, na.rm = TRUE)) %>% 
  ggplot(aes(x = appendage_number, y = avg_rating, fill = item)) +
  geom_bar(stat = "identity") +
  theme(legend.position = "none") +
  labs(x = "Base Shape", y = "Rating") +
  facet_wrap(~item)

appendage_data %>% 
  ggplot(aes(x = appendage_number, y = rating, fill = item)) +
  geom_boxplot() +
  geom_point(aes(x = appendage_number, y = rating), position=position_jitter(width =.15), size = 2, shape = 1) +
  theme(legend.position = "none") +
  labs(x = "Base Shape", y = "Rating") +
  facet_wrap(~item)

```
# How are entire fribbles rated?
```{r entire fribbles, echo = FALSE}

by_item_data %>% 
  group_by(item) %>% 
  summarise(avg_rating = mean(rating, na.rm = TRUE)) %>% 
  ggplot(aes(x = reorder(item, -avg_rating), y = avg_rating, fill = item)) +
  geom_bar(stat = "identity") +
  theme(legend.position = "none", axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  labs(x = "Entire Fribble (base + appendages)", y = "Rating")

by_item_data %>% 
  ggplot(aes(x = item, y = rating, fill = item)) +
  geom_boxplot() +
  geom_point(aes(x = item, y = rating), position=position_jitter(width =.15), size = 2, shape = 1) +
  theme(legend.position = "none", axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  labs(x = "Entire Fribble (base + appendages)", y = "Rating")

```
# Are there any where all components (e.g., base and appendages) are each individually rated high?
```{r all components separately, echo = FALSE}

components <- appendage_and_bases %>% 
  group_by(item, appendage_number) %>% 
  summarise(avg_rating = mean(rating, na.rm = TRUE))

components %>% 
  ggplot(aes(x = appendage_number, y = avg_rating, fill = appendage_number)) +
  geom_bar(stat = "identity") +
  facet_wrap(~item) +
  theme(legend.position = "none", axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  labs(x = "Appendage Number", y = "Average Rating")

appendage_and_bases %>% 
  ggplot(aes(x = appendage_number, y = rating, fill = appendage_number)) +
  geom_boxplot() +
  geom_point(aes(x = appendage_number, y = rating), position=position_jitter(width =.15), size = 2, shape = 1) +
  theme(legend.position = "none", axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  labs(x = "Base or Appendage Number", y = "Average Rating") +
  facet_wrap(~item)

```
# Which bases would you select?
```{r favorite bases, echo = FALSE}

choice_sums <- choice_data %>% 
  group_by(item) %>% 
  summarise(n = n())

choice_sums %>% 
  ggplot(aes(x = reorder(item, -n), y = n, fill = item)) +
  geom_bar(stat = "identity")  +
  theme(legend.position = "none", axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  labs(x = "Base Name", y = "Number of Times Nominanted") #All were chosen at least once!


test


```



```
